### ISSUE TITLE
missing license in repo

### ISSUE THREAD

**Issue by nijuyonkadesu** [stackhpc/pyhelm3#8]
## Description
I was working in my personal project, without licence, I am skeptical to use your helm library. 
Can you please look into this issue?

**Comment by scottblack1** [comment]
Likewise, I'd love to use this for a project but without the License this blocks some organizations from using it.

Is it possible we could add an OSS license for this project?

**Comment by mkjpryor** [comment]
Apache 2.0 license added. Apologies for the oversight.
